apiVersion: v1
kind: Service
metadata:
  name: nameserver-ssh
spec:
  selector:
    app.kubernetes.io/instance: rocketmq
    app.kubernetes.io/name: nameserver
  ports:
  - protocol: TCP
    port: 22
    targetPort: 2222
    name: ssh
  - port: 9876
    targetPort: 9876
    protocol: TCP
    name: nameserver
  type: ClusterIP

